task2: task2.c maxsum_tree.c 
	gcc -o task2 task2.c maxsum_tree.c	# links both files and external libraries

# main.o: task2.c maxsum_tree.h
# 	gcc -c task2.c						# assembles main.c into main.o

# maxsum_tree.o: maxsum_tree.c maxsum_tree.h
# 	gcc -c maxsum_tree.c		

clean: 
	rm task2.exe task2.o maxsum_tree.o